# used by our internal gitlab server

stages:
  - prepare
  - build
  - test
  - deploy

prepare:aten: # nightly
  stage: prepare
  script:
    - rm -rf _pytorch || yes
    - mkdir _pytorch
    - cd _pytorch
    - git clone -b fragcolor-devel https://$GITHUB_LOGIN@github.com/fragcolor-xyz/pytorch.git
    - cd pytorch
    - git remote add upstream https://github.com/pytorch/pytorch.git
    - git pull upstream master --no-edit
    - git push
    - git rev-parse HEAD > ../../torch/commit.txt
  tags:
    - LINUX
  # when: manual
  # allow_failure: false
  only:
    - triggers
    - schedules

prepare:aten: # normal
  stage: prepare
  script:
    - rm -rf _pytorch || yes
  tags:
    - LINUX
  except:
    - triggers
    - schedules

build:aten:native:
  stage: build
  script:
    - cd docker
    - docker build -f Dockerfile-aten-native -t docker_aten_native --build-arg TOKEN=$CONDA_TOKEN --build-arg BRANCH=$CI_COMMIT_REF_NAME --build-arg PYTORCH_COMMIT=`cat ../torch/commit.txt` .
  dependencies:
    - prepare:aten
  tags:
    - LINUX, DOCKER

build:aten:wasm:
  stage: build
  script:
    - cd docker
    - docker build -f Dockerfile-aten-wasm -t docker_aten_wasm --build-arg TOKEN=$CONDA_TOKEN --build-arg BRANCH=$CI_COMMIT_REF_NAME --build-arg PYTORCH_COMMIT=`cat ../torch/commit.txt` .
  dependencies:
    - prepare:aten
  tags:
    - LINUX, DOCKER
  
test:nimtorch:native:
  stage: test
  script:
    - nimble -y install fragments
    - docker run --name docker_aten_native-temp -d docker_aten_native /bin/bash
    - rm -rf output || yes
    - rm -rf nimcache || yes
    - docker cp docker_aten_native-temp:/root/pytorch/built/output output
    - export ATEN=`pwd`/output
    - nim cpp -r -o:test --nimcache:./nimcache torch/generator.nim
    - nim cpp -r -o:test --nimcache:./nimcache torch
    - nim cpp -r -o:test --nimcache:./nimcache torch/nn.nim
    - nim cpp -r -o:test --nimcache:./nimcache torch/nn/init.nim
    - nim cpp -r -o:test --nimcache:./nimcache torch/nn/functional.nim
    - nim cpp -r -o:test --nimcache:./nimcache tests/test_autograd.nim    
    - nim cpp -r -o:test --nimcache:./nimcache tests/test_xor.nim   
  after_script:
    - docker stop docker_aten_native-temp
    - docker rm docker_aten_native-temp
  dependencies:
    - build:aten:native
  tags:
    - LINUX, DOCKER, NIM, PYYAML

test:nimtorch:cuda:
  stage: test
  script:
    - nimble -y install fragments
    - docker run --name docker_aten_cuda-temp -d docker_aten_native /bin/bash
    - rm -rf output || yes
    - rm -rf nimcache || yes
    - docker cp docker_aten_cuda-temp:/root/pytorch/built/output output
    - export ATEN=`pwd`/output
    - export CUDA_INCLUDE=/opt/cuda/include
    - nim cpp -r -o:test --nimcache:./nimcache torch/generator.nim
    - nim cpp -r -o:test --nimcache:./nimcache -d:cuda torch
    - nim cpp -r -o:test --nimcache:./nimcache -d:cuda torch/nn.nim
    - nim cpp -r -o:test --nimcache:./nimcache -d:cuda torch/nn/init.nim
    - nim cpp -r -o:test --nimcache:./nimcache -d:cuda torch/nn/functional.nim
    - nim cpp -r -o:test --nimcache:./nimcache -d:cuda tests/test_autograd.nim
    - nim cpp -r -o:test --nimcache:./nimcache -d:cuda tests/test_xor.nim
  after_script:
    - docker stop docker_aten_cuda-temp
    - docker rm docker_aten_cuda-temp
  dependencies:
    - build:aten:native
  tags:
    - LINUX, DOCKER, NIM, PYYAML, CUDA, CONDA

test:nimtorch:wasm:
  stage: test
  script:
    - nimble -y install fragments
    - docker run --name docker_aten_wasm-temp -d docker_aten_wasm /bin/bash
    - rm -rf output || yes
    - rm -rf nimcache || yes
    - docker cp docker_aten_wasm-temp:/root/pytorch/built/output output
    - export ATEN=`pwd`/output
    - nim cpp -r -o:test --nimcache:./nimcache torch/generator.nim
    - nim cpp -d:wasm -d:release -o:test.js --nimcache:./nimcache torch
    - node test.js
    - nim cpp -d:wasm -d:release -o:test.js --nimcache:./nimcache torch/nn.nim
    - node test.js
    - nim cpp -d:wasm -d:release -o:test.js --nimcache:./nimcache tests/test_autograd.nim
    - node test.js
    - nim cpp -d:wasm -d:release -o:test.js --nimcache:./nimcache tests/test_xor.nim
    - node test.js
  after_script:
    - docker stop docker_aten_wasm-temp
    - docker rm docker_aten_wasm-temp
  dependencies:
    - build:aten:wasm
  tags:
    - LINUX, DOCKER, NIM, EMSCRIPTEN, PYYAML, CONDA