sudo: required

services:
  - docker

language: generic

os:
  - linux
  - osx

cache:
  directories:
  - $HOME/.nimtorch/
  - $HOME/.torch-folder/
  - $HOME/.conda/

notifications:
  slack:
    secure: GboTdvcsbPacYBE9XArFxryJdKwCXGPWGDDkgu1KgOc9R0rVvXfbPZ8WR4qEY/yeR/Dr7xphNazxB5mEfiloUjSbUeMTrdUafTQhXqNWJrSd88ZZ1DYN4EFmGCu3NXA1EjFdrP3zk2JOmldJtuAAg/Y4Th7kvmNyw2afR8LsCNEa2bVRZkJkTBhq9SJ9wNkhh4COlG0DMQK1sKPk613GuiTxB2tJNWWoueWv9tHoa+ZfRoG6PJKgumWl8uu3B5z6hSXc1byq9R6wya3CNOPcDmMFpM87D0fNWjg2+KxRfUEX6EQewG/PcUe2Wt54RYDzORMsv66N6sxi9Gv4mK8EKm3octTO330oWnyQflPfw2csPeYQ01d9+X2PmXXWiCf8SGNTqE5/BWCBxM5N5OVzTsrU9vL7LVecirtGPXWX1JshHVin7isi8i3uhAR7R6zddhHsMJesHj6Uqj79bBDPPZ5yWDoCtVsvGnclulc/uIGZmg96LX9v103iyGNWIyGvKj5oPeoxQQgnm+/APo1hJ53g/AHcmvBZhAgJs7SufWGq0ttacPFXWqNynKHSqY/Mu93LoZkgJUi5UDRjx7VyzREFHMTAj36hQPZvm8n/BmecoCwdUVVUu/RhmbzhGHhtNb+9o5cXpEJdqnz8k26wra/zFpFx2xlaSzk/4ZoIP10=

matrix:
  include:
  - stage: test
    name: "CPU Linux Tests"
    os: linux
    script:
    - set -e
    - docker build -f docker/Dockerfile-tests-cuda9.2 -t nimtorch-test --build-arg USER_ID=`id -u` --build-arg GROUP_ID=`id -g` --build-arg ATEN=`cat conda/nimtorch/meta.yaml | grep -o "aten ==[12][0-9]*.[01][0-9]*.[0-3][0-9]*.[0-9]*" | sed -r "s/aten /aten/g"` .
    - docker run --name test_nimtorch_native -t -u`id -u`:`id -g` nimtorch-test:latest nimble test
    - docker run --rm -t -u`id -u`:`id -g` nimtorch-test:latest nimble test_clang
  - stage: test
    name: "CPU macOS Tests"
    os: osx
    script:
    - set -e
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - export MACOSX_DEPLOYMENT_TARGET=10.13
    - conda create -n nimtorch_testing -c fragcolor nim=0.19.1 fragments=0.1.22 `cat conda/nimtorch/meta.yaml | grep -o "aten ==[12][0-9]*.[01][0-9]*.[0-3][0-9]*.[0-9]*" | sed -E "s/aten /aten/g"`
    - export ATEN=$HOME/miniconda/envs/nimtorch_testing
    - export PATH="$PATH:$HOME/miniconda/envs/nimtorch_testing/bin"
    - nimble test --nimcache:./nimcache
  - stage: test
    name: "WASM Tests"
    os: linux
    script:
    - set -e
    - docker build -f docker/Dockerfile-tests-wasm -t nimtorch-test --build-arg USER_ID=`id -u` --build-arg GROUP_ID=`id -g` --build-arg ATEN=`cat conda/nimtorch/meta.yaml | grep -o "aten ==[12][0-9]*.[01][0-9]*.[0-3][0-9]*.[0-9]*" | sed -r "s/aten /aten/g"` .
    - docker run --rm -t -u`id -u`:`id -g` nimtorch-test:latest nimble test_wasm
