sudo: required

services:
  - docker

language: generic

cache:
  directories:
  - $HOME/.nimtorch/
  - $HOME/.torch-folder/
  - $HOME/.conda/

notifications:
  slack:
    secure: GboTdvcsbPacYBE9XArFxryJdKwCXGPWGDDkgu1KgOc9R0rVvXfbPZ8WR4qEY/yeR/Dr7xphNazxB5mEfiloUjSbUeMTrdUafTQhXqNWJrSd88ZZ1DYN4EFmGCu3NXA1EjFdrP3zk2JOmldJtuAAg/Y4Th7kvmNyw2afR8LsCNEa2bVRZkJkTBhq9SJ9wNkhh4COlG0DMQK1sKPk613GuiTxB2tJNWWoueWv9tHoa+ZfRoG6PJKgumWl8uu3B5z6hSXc1byq9R6wya3CNOPcDmMFpM87D0fNWjg2+KxRfUEX6EQewG/PcUe2Wt54RYDzORMsv66N6sxi9Gv4mK8EKm3octTO330oWnyQflPfw2csPeYQ01d9+X2PmXXWiCf8SGNTqE5/BWCBxM5N5OVzTsrU9vL7LVecirtGPXWX1JshHVin7isi8i3uhAR7R6zddhHsMJesHj6Uqj79bBDPPZ5yWDoCtVsvGnclulc/uIGZmg96LX9v103iyGNWIyGvKj5oPeoxQQgnm+/APo1hJ53g/AHcmvBZhAgJs7SufWGq0ttacPFXWqNynKHSqY/Mu93LoZkgJUi5UDRjx7VyzREFHMTAj36hQPZvm8n/BmecoCwdUVVUu/RhmbzhGHhtNb+9o5cXpEJdqnz8k26wra/zFpFx2xlaSzk/4ZoIP10=

matrix:
  include:
  - stage: prepare
    name: "PyTorch merge"
    if: type = cron AND branch = master
    script:
    - set -e
    - git config --global user.email 'giovanni@fragcolor.xyz'
    - git config --global user.name 'Giovanni'
    - git clone -b fragcolor-devel https://$GITHUB_LOGIN@github.com/fragcolor-xyz/pytorch.git
    - cd pytorch
    - git remote add upstream https://github.com/pytorch/pytorch.git
    - git pull upstream master --no-edit
    - git push
    - git rev-parse HEAD > $HOME/.nimtorch/commit.txt
    - date +%Y.%m.%d.$TRAVIS_BUILD_NUMBER > $HOME/.nimtorch/version.txt
  - stage: build
    name: "Build CPU and cuda 9.2"
    if: type = cron AND branch = master
    script:
    - set -e
    - cd docker
    - sed -i -r "s/[12][0-9]{3}.[01][0-9].[0-3][0-9].[0-9]+/`cat $HOME/.nimtorch/version.txt`/g" conda/aten/meta.yaml
    - sed -i -r "s/[12][0-9]{3}.[01][0-9].[0-3][0-9].[0-9]+/`cat $HOME/.nimtorch/version.txt`/g" conda/aten_cuda10.0/meta.yaml
    - sed -i -r "s/[12][0-9]{3}.[01][0-9].[0-3][0-9].[0-9]+/`cat $HOME/.nimtorch/version.txt`/g" conda/aten_wasm/meta.yaml
    - docker pull nvidia/cuda:9.2-devel-ubuntu18.04
    - docker build -f Dockerfile-aten-cuda9.2 -t docker_aten_cuda92 --build-arg TOKEN=$CONDA_TOKEN --build-arg PYTORCH_COMMIT=`cat $HOME/.nimtorch/commit.txt` .
  - stage: build
    name: "Build CPU and cuda 10.0"
    if: type = cron AND branch = master
    script:
    - set -e
    - cd docker
    - sed -i -r "s/[12][0-9]{3}.[01][0-9].[0-3][0-9].[0-9]+/`cat $HOME/.nimtorch/version.txt`/g" conda/aten/meta.yaml
    - sed -i -r "s/[12][0-9]{3}.[01][0-9].[0-3][0-9].[0-9]+/`cat $HOME/.nimtorch/version.txt`/g" conda/aten_cuda10.0/meta.yaml
    - sed -i -r "s/[12][0-9]{3}.[01][0-9].[0-3][0-9].[0-9]+/`cat $HOME/.nimtorch/version.txt`/g" conda/aten_wasm/meta.yaml
    - docker pull nvidia/cuda:10.0-devel-ubuntu18.04
    - docker build -f Dockerfile-aten-cuda10.0 -t docker_aten_cuda10 --build-arg TOKEN=$CONDA_TOKEN --build-arg PYTORCH_COMMIT=`cat $HOME/.nimtorch/commit.txt` .
  - stage: build
    name: "Build WASM"
    if: type = cron AND branch = master
    script:
    - set -e
    - cd docker
    - sed -i -r "s/[12][0-9]{3}.[01][0-9].[0-3][0-9].[0-9]+/`cat $HOME/.nimtorch/version.txt`/g" conda/aten/meta.yaml
    - sed -i -r "s/[12][0-9]{3}.[01][0-9].[0-3][0-9].[0-9]+/`cat $HOME/.nimtorch/version.txt`/g" conda/aten_cuda10.0/meta.yaml
    - sed -i -r "s/[12][0-9]{3}.[01][0-9].[0-3][0-9].[0-9]+/`cat $HOME/.nimtorch/version.txt`/g" conda/aten_wasm/meta.yaml
    - docker pull base/devel
    - docker build -f Dockerfile-aten-wasm -t docker_aten_wasm --build-arg TOKEN=$CONDA_TOKEN --build-arg PYTORCH_COMMIT=`cat $HOME/.nimtorch/commit.txt` .
  - stage: bump # Aten build was a success, bump versions
    name: "New aten version"
    if: type = cron AND branch = master
    script:
    - set -e
    - sed -i -r "s/[12][0-9]{3}.[01][0-9].[0-3][0-9].[0-9]+/`cat $HOME/.nimtorch/version.txt`/g" conda/nimtorch/meta.yaml
    - cp conda/nimtorch/meta.yaml $HOME/.conda/
  - stage: bump # Pass old version
    name: "Using previous aten version"
    if: type != cron
    script:
    - set -e
    - cp conda/nimtorch/meta.yaml $HOME/.conda/
  - stage: test
    name: "CPU Tests"
    script:
    - set -e
    - docker build -f docker/Dockerfile-tests-cuda9.2 -t nimtorch-test --build-arg USER_ID=`id -u` --build-arg GROUP_ID=`id -g` --build-arg ATEN=`cat $HOME/.conda/meta.yaml | grep -o "aten ==[12][0-9]*.[01][0-9]*.[0-3][0-9]*.[0-9]*" | sed -r "s/aten /aten/g"` .
    - docker run --name test_nimtorch_native -t -u`id -u`:`id -g` nimtorch-test:latest nimble test
    - docker cp test_nimtorch_native:/home/tester/nimtorch/torch $HOME/.torch-folder/ # copy any new artifact from generator.nim
    - docker run --rm -t -u`id -u`:`id -g` nimtorch-test:latest nimble test_clang
  - stage: test
    name: "WASM Tests"
    script:
    - set -e
    - docker build -f docker/Dockerfile-tests-wasm -t nimtorch-test --build-arg USER_ID=`id -u` --build-arg GROUP_ID=`id -g` --build-arg ATEN=`cat $HOME/.conda/meta.yaml | grep -o "aten ==[12][0-9]*.[01][0-9]*.[0-3][0-9]*.[0-9]*" | sed -r "s/aten /aten/g"` .
    - docker run --rm -t -u`id -u`:`id -g` nimtorch-test:latest nimble test_wasm
