sudo: required

services:
  - docker

matrix:
  include:
  - name: "CPU Only GCC Tests"
    language: generic
    env:
    - CONTAINER=Dockerfile-tests-cuda9.2
    - TEST=test
  - name: "CPU Only clang Tests"
    language: generic
    env:
    - CONTAINER=Dockerfile-tests-cuda9.2
    - TEST=test_clang
  - name: "WASM Tests"
    language: generic
    env:
    - CONTAINER=Dockerfile-tests-wasm
    - TEST=test_wasm

script:
- docker build -f docker/$CONTAINER -t nimtorch-test --build-arg USER_ID=`id -u` --build-arg GROUP_ID=`id -g` --build-arg ATEN=`cat conda/nimtorch/meta.yaml | grep -o "aten ==[12][0-9]*.[01][0-9]*.[0-3][0-9]*.[0-9]*" | sed -r "s/aten /aten/g"` .
- docker run --name test_nimtorch -t -u`id -u`:`id -g` nimtorch-test:latest nimble $TEST
